### ISSUE TITLE
Support custom model data

### ISSUE THREAD

**Issue by RICE0707** [ArtformGames/ResidenceList#49]
As title

**Comment by CarmJos** [comment]
Do you mean support custom-model-data in custom icons?

**Comment by RICE0707** [comment]
> Do you mean support custom-model-data in custom icons?

yes
Also includes gui

**Comment by CarmJos** [comment]
> > Do you mean support custom-model-data in custom icons?
> 
> yes Also includes gui

For gui icons, you can simply add `custom-model-data: 0` entry at each icon's configuration section to support it.

**Comment by RICE0707** [comment]
> > > Do you mean support custom-model-data in custom icons?
> > 
> > 
> > yes Also includes gui
> 
> For gui icons, you can simply add `custom-model-data: 0` entry at each icon's configuration section to support it.

了解，不過我也希望 Shift + 左右鍵 自定義圖標的物品可以支援 custom model data

**Comment by CarmJos** [comment]
> > > > Do you mean support custom-model-data in custom icons?
> > > 
> > > 
> > > yes Also includes gui
> > 
> > 
> > For gui icons, you can simply add `custom-model-data: 0` entry at each icon's configuration section to support it.
> 
> 了解，不過我也希望 Shift + 左右鍵 自定義圖標的物品可以支援 custom model data

明白，但这个可能需要再下一个主版本中才能支持了。

**Comment by CarmJos** [comment]
您好，请您下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/10906540609/artifacts/1943508111) 以协助我们测试本功能，万分感谢！

**Comment by RICE0707** [comment]
> 您好，请您下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/10906540609/artifacts/1943508111) 以协助我们测试本功能，万分感谢！

正常運作
![image](https://github.com/user-attachments/assets/e428715c-6300-4ba1-8f05-82d5222b5a79)

**Comment by CarmJos** [comment]
感谢您的帮助，此版本将在稍后发版。
