### ISSUE TITLE
gui item HIDE_ATTRIBUTES

### ISSUE THREAD

**Issue by RICE0707** [ArtformGames/ResidenceList#56]
![image](https://github.com/user-attachments/assets/0d7b137d-91e3-4fd9-8195-6b571d6ba301)
如圖所示，希望 GUI 物品可以隱藏屬性。

**Comment by CarmJos** [comment]
For gui icons, you can easily add "flags" section to support this function.

In next version, "flags" for user's custom icons will be supported.

**Comment by CarmJos** [comment]
For all supported config sections, see https://github.com/CryptoMorin/XSeries/wiki/XItemStack .

**Comment by CarmJos** [comment]
另外，那个领地大小是领地内方块总数，因此应该是“立方公尺”才对。

**Comment by RICE0707** [comment]
> 另外，那个领地大小是领地内方块总数，因此应该是“立方公尺”才对。

我的伺服器設置領地的 Y 高度是預設框選最高到最低，
玩家設置領地時以平面設置兩點，其格數顯示也會是平面的格數
