### ISSUE TITLE
Bug: 鼠标中键无法打开领地图标设置页面

### ISSUE THREAD

**Issue by SuperBeacon** [ArtformGames/ResidenceList#65]
### **Description**

版本: 1.18.1paper

### **Environment**

- System: `Windows 10` / `Ubuntu` / `...`
- Java version: `JDK11` / `OPENJDK8` / `JRE8` / `...`

**Comment by Sraconni** [comment]
Issues #51 已报告该问题，并在 Release [1.2.3](https://github.com/ArtformGames/ResidenceList/releases/tag/1.2.3) 版本中修复，请勿重复提交issues。

**Comment by SuperBeacon** [comment]
并不是重复提交，而是在我这边又再次出现了这个问题

**Comment by Sraconni** [comment]
> 并不是重复提交，而是在我这边又再次出现了这个问题

Hum，可以提供更为详细的描述吗，或者可能的复现的方式，以便我们定位问题。

**Comment by SuperBeacon** [comment]
> > 并不是重复提交，而是在我这边又再次出现了这个问题
> 
> Hum，可以提供更为详细的描述吗，或者可能复现的方式，以便我们定位问题。

但是也确实我这边并没有任何报错，在鼠标中键点击后无任何反应，版本: 1.18.1paper

**Comment by Sraconni** [comment]
> > 并不是重复提交，而是在我这边又再次出现了这个问题
> 
> Hum，可以提供更为详细的描述吗，或者可能复现的方式，以便我们定位问题。

还有，由于高版本的变更，生存模式中不再检测中键单击事​​件，所以在 Release [1.2.3](https://github.com/ArtformGames/ResidenceList/releases/tag/1.2.3) 版本的修复，已经将中键编辑图标改为Shift+左右键单击的方式，您是否有注意到这一变更。

**Comment by SuperBeacon** [comment]
哦，这样啊，不好意思，没有留意到

> > > 并不是重复提交，而是在我这边又再次出现了这个问题
> > 
> > 
> > Hum，可以提供更为详细的描述吗，或者可能复现的方式，以便我们定位问题。
> 
> 还有，由于高版本的变更，生存模式中不再检测中键单击事​​件，所以在 Release [1.2.3](https://github.com/ArtformGames/ResidenceList/releases/tag/1.2.3) 版本的修复，已经将中键编辑图标改为Shift+左右键单击的方式，您是否有注意到这一变更。

**Comment by SuperBeacon** [comment]
嗯，我刚刚试了可以打开，没有其他问题了
