### ISSUE TITLE
#62 尚未解決

### ISSUE THREAD

**Issue by RICE0707** [ArtformGames/ResidenceList#67]
使用了 #62 提供的插件檔案後，
` auto-remove `設置並沒有實際效果，

ResidenceList/config.yml
```
settings:
  auto-remove: true
```

**Comment by RICE0707** [comment]
並且這個設定不存在於插件生成的 config 當中

**Comment by CarmJos** [comment]
请下载 [此构件](https://github.com/ArtformGames/ResidenceList/actions/runs/11340154515/artifacts/2056365854) 重试，请注意新版本为 1.3.2， 务必删除旧的插件。

**Comment by RICE0707** [comment]
經測試後，config 有正常產生  auto-remove 設置，至於是否有功能，我明天回復你
```
settings:
  # Remove info data when failed to load.
  #   true = Delete the info data, false = Only notify, keep the info data.
  auto-remove: true
  ```

**Comment by RICE0707** [comment]
經確認後，檔案有正常刪除。

**Comment by CarmJos** [comment]
好的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月18日(周五) 上午9:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ArtformGames/ResidenceList] #62 尚未解決 (Issue #67)




 
經確認後，檔案有正常刪除。
